"""'Watch & Learn' Macro Recorder: Compiles visual action sequences into deterministic scripts."""

import re
from pathlib import Path
from typing import Any, Dict, List, Optional
from jarvis.actuators.base import ActionResult
from jarvis.actuators.python_runner import PythonRunner

WORKFLOWS_DIR = Path.home() / ".jarvis" / "memory" / "workflows"

class MacroRecorder:
    def __init__(self, workflows_dir: Optional[Path] = None):
        self.workflows_dir = workflows_dir or WORKFLOWS_DIR
        self.workflows_dir.mkdir(parents=True, exist_ok=True)
        self.runner = PythonRunner()

    def compile_macro(self, macro_name: str, step_records: List[Dict[str, Any]]) -> Path:
        """Compile a list of recorded action steps into a deterministic Python script."""
        safe_name = re.sub(r"[^a-zA-Z0-9_-]", "_", macro_name.lower())
        script_file = self.workflows_dir / f"{safe_name}.py"

        code_lines = [
            "# Auto-generated by Jarvis 'Watch & Learn' Macro Recorder",
            f"# Macro: {macro_name}",
            "import time",
            "import pyautogui",
            "from playwright.sync_api import sync_playwright",
            "",
            "def run():",
            "    print('▶ Executing compiled macro: " + macro_name + "')",
        ]

        for step in step_records:
            action = step.get("action", "")
            params = step.get("params", {})

            if action == "desktop_click":
                x = params.get("x", 0)
                y = params.get("y", 0)
                code_lines.append(f"    pyautogui.click({x}, {y})")
                code_lines.append("    time.sleep(0.3)")
            elif action == "desktop_type":
                text = params.get("text", "").replace("'", "\\'")
                code_lines.append(f"    pyautogui.write('{text}')")
                code_lines.append("    time.sleep(0.2)")
            elif action == "desktop_press_key":
                key = params.get("key", "enter")
                code_lines.append(f"    pyautogui.press('{key}')")
                code_lines.append("    time.sleep(0.2)")
            elif action == "browser_navigate":
                url = params.get("url", "")
                code_lines.append("    # Browser step:")
                code_lines.append("    with sync_playwright() as p:")
                code_lines.append("        b = p.chromium.launch(headless=False)")
                code_lines.append(f"        page = b.new_page()")
                code_lines.append(f"        page.goto('{url}')")
                code_lines.append("        time.sleep(1)")
                code_lines.append("        b.close()")

        code_lines.extend([
            "    print('✔ Macro completed successfully')",
            "",
            "if __name__ == '__main__':",
            "    run()",
        ])

        script_file.write_text("\n".join(code_lines), encoding="utf-8")
        return script_file

    def run_macro(self, macro_name: str) -> ActionResult:
        """Execute a compiled macro script directly."""
        safe_name = re.sub(r"[^a-zA-Z0-9_-]", "_", macro_name.lower())
        script_file = self.workflows_dir / f"{safe_name}.py"
        if not script_file.exists():
            return ActionResult(success=False, error=f"Macro script '{safe_name}.py' not found.")

        return self.runner.run_file(str(script_file))
